#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(docs|feat|fix|refactor|test)(\(.+?\))?!?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    cat "$1"
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
    echo "Aborting commit. Your commit message is too long. Max 100 characters allowed." >&2
    exit 1
fi